### PR TITLE
Compatibility v3.0.0

### PR DESCRIPTION
**Pull request by BenjaminRodenberg**
Ensures compatibility to preCICE v3.0.0.

This PR should work with https://github.com/precice/precice/tree/develop-v3.0.0.

### CODE REVIEW

**Comment by IshaanDesai** [comment]
Can we sync this with the latest develop to ensure that when we plan to merge this we would not have excessive conflicts?

**Comment by BenjaminRodenberg** [comment]
> Can we sync this with the latest develop to ensure that when we plan to merge this we would not have excessive conflicts?

Done.

**Comment by IshaanDesai** [comment]
Since https://github.com/precice/precice/pull/1366 has now been merged upstream, we can also start moving the bindings to v3.0.0. @BenjaminRodenberg should we start by merging this PR? I am open to suggestions if you already have some order of doing things in mind.

**Comment by BenjaminRodenberg** [comment]
As far as my plans are concerned this PR should be ready to merge. I think another round of manual testing does not harm. @IshaanDesai Feel free to play around with the current develop state of preCICE and this PR. I think this is a good step to understand the upcoming changes in preCICE as well.

If after testing everything looks good, you can just merge. If you find something that is not documented or broken, this is a good thing to fix before merging.

**Review by IshaanDesai — APPROVED** [review]
I did some manual testing and everything seems to be in order for now. If something does break, we can fix it post merge.

**Pull request merged**
