### PR TITLE
Release v2.2.1.1

### PR DESCRIPTION
**Pull request by IshaanDesai**
This release is required due to a [bug fix release of preCICE v2.2.1](https://github.com/precice/precice/pull/1023)

Features of this release:
* Removing Travis CI
* Adding tests to check autopep8 formatting, building dockerimage

### CODE REVIEW

**Comment by IshaanDesai** [comment]
@BenjaminRodenberg is the Spack build expected to fail right now?

**Review by BenjaminRodenberg — APPROVED** [review]
From my side this PR looks good.

The failing spack test is a tricky issue. I assume that this is a problem on precice@develop and not on precice@2.2.1. However, we currently don't know, since we do not test using precice@2.2.1. From my perspective a manual test with precice@2.2.1 should be sufficient for this release. On the long run we should think about our testing strategy

1. for the python bindings, when the spack environment is updated (weekly cron job)
2. for precice, since we currently don't have any information on the status of the spack package precice@develop.

**Comment by ajaust** [comment]
The failing Spack build might be simply a Spack artifact when using the Python module in a fresh Spack environment. However, the Spack environment is not touched/changed.

It could also be related https://github.com/precice/python-bindings/issues/86 which means that the Python module is installed to a location where we do not expect/want it to be. Maybe the module is in the environment of a/the wrong Python installation. At least the output suggest that the Python modules was built and installed successfully.

**Comment by ajaust** [comment]
I just restarted the failing test twice and now it passed twice. I am not sure what to conclude here. I would guess this PR is fine for now.

**Pull request merged**
